deployments:
  services:
    ids:
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlLzdhMjM5NzNiLTM2MjctNGQxNy1hMDAyLWY4Y2M0NDM4YTUzNi8zMzJmNGViYy0xNmIyLTExZjAtYjYxNi0wYWZmZjI1ZmQ5MzM=
    - b:YXJpOmNsb3VkOmdyYXBoOjpzZXJ2aWNlL2E1ZTc5Yzc5LThjZjMtNDE0Yi1hZmY4LTZhNDJhY2RkMjJhZC9lYzRiOTMzNC0yYWEyLTExZjAtOWU2Yi0wYWZmZjI1ZmQ5MzM=
